### PR TITLE
Features

### PR DESCRIPTION
**Pull request by carlos-ssh**
TSE's Project Review:

This Project was created on RoR, installed a few gems, bootstrap and created some views like links with comments and you can vote over every Link, edited, destroy etc.
This project was tested over localhost and installed rubocop for fix issues in the project.

Thanks for your time and happy holidays.

Carlos-SSH

### CODE REVIEW

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️

#### Hey team,  your project is looking really good, however, to accomplish as the actual project, you required to do these changes, listed below:

 
## [REQUIRED CHANGES]
Please note that we should have users, posts and comments. I don't quite get what you meant by "link".
I also had some issues to run your project, something with the gem 'bundler', '2.2.2'
Please take a look on the comments below and improve your project, using correct naming and associations.
##### User

- [x] username is validated (at least for the presence) **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/userValidation.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))
- [x] `has_many :posts` **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/user_has_many_posts.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))
- [x] `has_many :comments` **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/user_has_many_comments.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))


##### Post

- [x] validations are present (`body` and `title` in automated tests but can be anything else) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/postValidation.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))
- [x] `belongs_to :user` **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/post_belongs_to_a_user.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))
- [x] `has_many :comments` **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/post_has_many_comments.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))

##### Comment

- [x] validations are present (`body` in automated tests but can be anything else) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/commentValidation.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))
- [x] `belongs_to :user` **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/comment_belongs_to_a_user.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))
- [x] `belongs_to :post` **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/comment_belongs_to_a_post.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))

- [x] You also should update your readme!
## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In the real world, you'll have a lot of change requests for your real clients, it's good to get used to it.</sub>

**Comment by carlos-ssh** [comment]
**Hi @kevincappuccino  Thank you for you feedback i worked with the requested changes and i check my bundler -v in my terminal that says that is it working with the described _version "2.2.2"_. 

I updated the gem and then installed with bundler.**


- **"Links"** are **"Posts"**.

**I do this changes:**

**User:**
- Username is validated (at least for the presence) (covered by automated tests).
- has_many :posts (covered by automated tests).
- has_many :comments (covered by automated tests).

**Post:**
- validations are present (body and title in automated tests).
- belongs_to :user (covered by automated tests).
- has_many :comments (covered by automated tests).

**Comment:**
- validations are present (body in automated tests).
- belongs_to :user (covered by automated tests).
- belongs_to :post (covered by automated tests).

**_Readme File_ was Updated.**

_Thanks again!_
**Carlos-SSH**

**Review by javitocor — CHANGES_REQUESTED** [review]
# STATUS CHANGES REQUIRED ♻️ 

Hello 👋 
Good job implementing some of the requested changes! 👍 
However, we still need a bit more to get the project approved 💪 
Kindly check my comments below 👇  apply the changes and resubmit your project for a new code review ⏩ 
Good luck 😺 
## Mandatory changes
- Add the license to your repo
- Remember to validate all the links fields in your model, we need to be safe with all our inputs
- Kindly remove all the commented out code, for example in your controller's
- Kindly remove all the JSON responses in your controller since your are not using them
- Use only the actions that are necessary, if you are not using a destroy action do not implement it
- In your routes, kindly add only the resources necessary aka the routes/actions you are using.
- Do not replicate resources in your routes.rb file

**Comment by carlos-ssh** [comment]
**I made this requested changes:** 

- Added the license to this project.
- Validated all the links fields in your model.
- Removed commented out code (in controller's)
- Removed all the JSON responses in controller.
- Removed a destroy action in controllers.
- Added resources necessary only the routes/actions.
- Removed replicated resources in routes.rb file.

**Greetings.**

**Carlos-SSH**

**Review by voscarmv — APPROVED** [review]
# Project status: Approved ✨ 😎👍 💯 ✔️

- Excellent work applying all the necessary changes.

### You may merge this branch and move forward ⛙🛣

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Pull request merged**
